"""add knowledge_base_id column to apps

Revision ID: 34f136b2b0b6
Revises: a1b2c3d4e5f6
Create Date: 2025-10-15 09:56:24.513322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34f136b2b0b6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'apps',
        sa.Column('knowledge_base_id', sa.Integer(), nullable=True))
    op.alter_column(
        'messages', 'content',
        existing_type=mysql.LONGTEXT(),
        type_=sa.Text(),
        existing_nullable=False
    )
    op.alter_column(
        'prompt_versions', 'content',
        existing_type=mysql.LONGTEXT(),
        type_=sa.Text(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'prompt_versions', 'content',
        existing_type=sa.Text(),
        type_=mysql.LONGTEXT(),
        existing_nullable=False
    )
    op.alter_column(
        'messages', 'content',
        existing_type=sa.Text(),
        type_=mysql.LONGTEXT(),
        existing_nullable=False
    )
    op.drop_column('apps', 'knowledge_base_id')
    # ### end Alembic commands ###
