"""create jobs table

Revision ID: 9c130e8c6c92
Revises: 34f136b2b0b6
Create Date: 2025-10-15 16:42:43.543928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c130e8c6c92"
down_revision: Union[str, None] = "34f136b2b0b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("app_id", sa.String(length=100), nullable=True),
        sa.Column("job_type", sa.String(length=75), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("input_data", sa.Text(), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("callback_url", sa.String(length=850), nullable=True),
        sa.Column("callback_params", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=110), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
