"""Drop FK from chat_knowledge_bases

Revision ID: f6f5943ad151
Revises: 426b79846bc6
Create Date: 2025-09-18 16:48:17.029000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6f5943ad151"
down_revision: Union[str, None] = "426b79846bc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop only the foreign key constraint, keep the column and existing data
    op.drop_constraint(
        op.f("chat_knowledge_bases_ibfk_2"),
        "chat_knowledge_bases",
        type_="foreignkey",
    )
    # Column remains Integer, data is preserved
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add the foreign key constraint
    op.create_foreign_key(
        op.f("chat_knowledge_bases_ibfk_2"),
        "chat_knowledge_bases",
        "knowledge_bases",
        ["knowledge_base_id"],
        ["id"],
    )
    # ### end Alembic commands ###
